language: ruby
rvm:
  - 1.9.3
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - rbx-18mode
  - rbx-19mode
  - 1.8.7
  - ree

services: sqlite3

matrix:
  allow_failures:
    rvm:
      - jruby-19mode
      - jruby-head